spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spaceship?autoReconnect=true&useSSL=false
    username: root
    password: 
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
   # generate-ddl: true
    #hibernate.ddl-auto: create
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
