/*
 * Spaceship Protocal API
 * Spaceship Protocal API help for commincate between spaceships
 * OpenAPI spec version: 1.0
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spaceship.protocal.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-18T22:37:13.441Z")
public class GameResponse {
    @SerializedName("fullName")
    private String fullName = null;

    @SerializedName("gameId")
    private String gameId = null;

    @SerializedName("starting")
    private String starting = null;

    @SerializedName("userId")
    private String userId = null;

    @SerializedName("winner")
    private String winner;

    @SerializedName("status")
    private String status;

    public GameResponse fullName(String fullName) {
        this.fullName = fullName;
        return this;
    }

    /**
     * @return the winner
     */
    @ApiModelProperty(example = "null", value = "")
    public String getWinner() {
        return winner;
    }

    /**
     * @param winner
     *        the winner to set
     */
    public void setWinner(String winner) {
        this.winner = winner;
    }

    /**
     * @return the status
     */
    @ApiModelProperty(example = "null", value = "")
    public String getStatus() {
        return status;
    }

    /**
     * @param status
     *        the status to set
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Get fullName
     *
     * @return fullName
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public GameResponse gameId(String gameId) {
        this.gameId = gameId;
        return this;
    }

    /**
     * Get gameId
     *
     * @return gameId
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public GameResponse starting(String starting) {
        this.starting = starting;
        return this;
    }

    /**
     * Get starting
     *
     * @return starting
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getStarting() {
        return starting;
    }

    public void setStarting(String starting) {
        this.starting = starting;
    }

    public GameResponse userId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     *
     * @return userId
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GameResponse inlineResponse200 = (GameResponse) o;
        return Objects.equals(this.fullName, inlineResponse200.fullName) && Objects.equals(this.gameId, inlineResponse200.gameId) && Objects.equals(this.starting, inlineResponse200.starting)
                && Objects.equals(this.userId, inlineResponse200.userId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fullName, gameId, starting, userId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse200 {\n");

        sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
        sb.append("    gameId: ").append(toIndentedString(gameId)).append("\n");
        sb.append("    starting: ").append(toIndentedString(starting)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
