/*
 * Spaceship Protocal API
 * Spaceship Protocal API help for commincate between spaceships
 * OpenAPI spec version: 1.0
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spaceship.protocal.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * XlspaceshipprotocolgamenewPlayers
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-18T22:37:13.441Z")
public class GamePlayer {
    @SerializedName("full_name")
    private String fullName = null;

    /**
     * Gets or Sets playerType
     */
    public enum PlayerTypeEnum {
        @SerializedName("OPPONENT")
        OPPONENT("OPPONENT"),

        @SerializedName("ASSESSMENT")
        ASSESSMENT("ASSESSMENT");

        private String value;

        PlayerTypeEnum(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }

    @SerializedName("playerType")
    private PlayerTypeEnum playerType = null;

    @SerializedName("spaceship_protocol")
    private XLSpaceshipProtocol spaceshipProtocol = null;

    @SerializedName("user_id")
    private String userId = null;

    public GamePlayer fullName(String fullName) {
        this.fullName = fullName;
        return this;
    }

    /**
     * Get fullName
     *
     * @return fullName
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public GamePlayer playerType(PlayerTypeEnum playerType) {
        this.playerType = playerType;
        return this;
    }

    /**
     * Get playerType
     *
     * @return playerType
     **/
    @ApiModelProperty(example = "null", value = "")
    public PlayerTypeEnum getPlayerType() {
        return playerType;
    }

    public void setPlayerType(PlayerTypeEnum playerType) {
        this.playerType = playerType;
    }

    public GamePlayer spaceshipProtocol(XLSpaceshipProtocol spaceshipProtocol) {
        this.spaceshipProtocol = spaceshipProtocol;
        return this;
    }

    /**
     * Get spaceshipProtocol
     *
     * @return spaceshipProtocol
     **/
    @ApiModelProperty(example = "null", value = "")
    public XLSpaceshipProtocol getSpaceshipProtocol() {
        return spaceshipProtocol;
    }

    public void setSpaceshipProtocol(XLSpaceshipProtocol spaceshipProtocol) {
        this.spaceshipProtocol = spaceshipProtocol;
    }

    public GamePlayer userId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     *
     * @return userId
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GamePlayer xlspaceshipprotocolgamenewPlayers = (GamePlayer) o;
        return Objects.equals(this.fullName, xlspaceshipprotocolgamenewPlayers.fullName) && Objects.equals(this.playerType, xlspaceshipprotocolgamenewPlayers.playerType)
                && Objects.equals(this.spaceshipProtocol, xlspaceshipprotocolgamenewPlayers.spaceshipProtocol) && Objects.equals(this.userId, xlspaceshipprotocolgamenewPlayers.userId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fullName, playerType, spaceshipProtocol, userId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class XlspaceshipprotocolgamenewPlayers {\n");

        sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
        sb.append("    playerType: ").append(toIndentedString(playerType)).append("\n");
        sb.append("    spaceshipProtocol: ").append(toIndentedString(spaceshipProtocol)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
