/*
 * Spaceship Protocal API
 * Spaceship Protocal API help for commincate between spaceships
 * OpenAPI spec version: 1.0
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spaceship.protocal.client.model;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2001
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-18T22:37:13.441Z")
public class GameStatusResponse {
    @SerializedName("game")
    private Map<String, String> game = new HashMap<String, String>();

    @SerializedName("opponent")
    private InlineResponse2001Opponent opponent = null;

    @SerializedName("self")
    private InlineResponse2001Opponent self = null;

    public GameStatusResponse game(Map<String, String> game) {
        this.game = game;
        return this;
    }

    public GameStatusResponse putGameItem(String key, String gameItem) {
        this.game.put(key, gameItem);
        return this;
    }

    /**
     * Get game
     *
     * @return game
     **/
    @ApiModelProperty(example = "null", value = "")
    public Map<String, String> getGame() {
        return game;
    }

    public void setGame(Map<String, String> game) {
        this.game = game;
    }

    public GameStatusResponse opponent(InlineResponse2001Opponent opponent) {
        this.opponent = opponent;
        return this;
    }

    /**
     * Get opponent
     *
     * @return opponent
     **/
    @ApiModelProperty(example = "null", value = "")
    public InlineResponse2001Opponent getOpponent() {
        return opponent;
    }

    public void setOpponent(InlineResponse2001Opponent opponent) {
        this.opponent = opponent;
    }

    public GameStatusResponse self(InlineResponse2001Opponent self) {
        this.self = self;
        return this;
    }

    /**
     * Get self
     *
     * @return self
     **/
    @ApiModelProperty(example = "null", value = "")
    public InlineResponse2001Opponent getSelf() {
        return self;
    }

    public void setSelf(InlineResponse2001Opponent self) {
        this.self = self;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GameStatusResponse inlineResponse2001 = (GameStatusResponse) o;
        return Objects.equals(this.game, inlineResponse2001.game) && Objects.equals(this.opponent, inlineResponse2001.opponent) && Objects.equals(this.self, inlineResponse2001.self);
    }

    @Override
    public int hashCode() {
        return Objects.hash(game, opponent, self);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse2001 {\n");

        sb.append("    game: ").append(toIndentedString(game)).append("\n");
        sb.append("    opponent: ").append(toIndentedString(opponent)).append("\n");
        sb.append("    self: ").append(toIndentedString(self)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
