/*
 * Spaceship Protocal API
 * Spaceship Protocal API help for commincate between spaceships
 * OpenAPI spec version: 1.0
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spaceship.protocal.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2001Opponent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-18T22:37:13.441Z")
public class InlineResponse2001Opponent {
    @SerializedName("board")
    private List<List<String>> board = new ArrayList<List<String>>();

    @SerializedName("user_id")
    private String userId = null;

    public InlineResponse2001Opponent board(List<List<String>> board) {
        this.board = board;
        return this;
    }

    public InlineResponse2001Opponent addBoardItem(List<String> boardItem) {
        this.board.add(boardItem);
        return this;
    }

    /**
     * Get board
     *
     * @return board
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<List<String>> getBoard() {
        return board;
    }

    public void setBoard(List<List<String>> board) {
        this.board = board;
    }

    public InlineResponse2001Opponent userId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     *
     * @return userId
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InlineResponse2001Opponent inlineResponse2001Opponent = (InlineResponse2001Opponent) o;
        return Objects.equals(this.board, inlineResponse2001Opponent.board)
                && Objects.equals(this.userId, inlineResponse2001Opponent.userId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(board, userId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InlineResponse2001Opponent {\n");

        sb.append("    board: ").append(toIndentedString(board)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
