/*
 * Spaceship Protocal API
 * Spaceship Protocal API help for commincate between spaceships
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.spaceship.protocal.client.model;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2002
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-18T22:37:13.441Z")
public class InlineResponse2002 {
  @SerializedName("game")
  private Map<String, String> game = new HashMap<String, String>();

  @SerializedName("salvo")
  private Map<String, String> salvo = new HashMap<>();

  public InlineResponse2002 game(Map<String, String> game) {
    this.game = game;
    return this;
  }

  public InlineResponse2002 putGameItem(String key, String gameItem) {
    this.game.put(key, gameItem);
    return this;
  }

   /**
   * Get game
   * @return game
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getGame() {
    return game;
  }

  public void setGame(Map<String, String> game) {
    this.game = game;
  }

  public InlineResponse2002 salvo(Map<String, String> salvo) {
    this.salvo = salvo;
    return this;
  }


   /**
   * Get salvo
   * @return salvo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getSalvo() {
    return salvo;
  }

  public void setSalvo(Map<String, String> salvo) {
    this.salvo = salvo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.game, inlineResponse2002.game) &&
        Objects.equals(this.salvo, inlineResponse2002.salvo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(game, salvo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");

    sb.append("    game: ").append(toIndentedString(game)).append("\n");
    sb.append("    salvo: ").append(toIndentedString(salvo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

