/*
 * Spaceship Protocal API
 * Spaceship Protocal API help for commincate between spaceships
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.spaceship.protocal.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
