/*
 * User Protocal API
 * User Protocal API help for commincate between users
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.spaceship.user.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * UserVo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-19T16:17:59.908Z")
public class UserVo {
  @SerializedName("fullName")
  private String fullName = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("spaceShips")
  private List<XlspaceshipusergetAllOpponentUsersSpaceShips> spaceShips = new ArrayList<XlspaceshipusergetAllOpponentUsersSpaceShips>();

  @SerializedName("userId")
  private String userId = null;

  public UserVo fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public UserVo id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public UserVo password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UserVo spaceShips(List<XlspaceshipusergetAllOpponentUsersSpaceShips> spaceShips) {
    this.spaceShips = spaceShips;
    return this;
  }

  public UserVo addSpaceShipsItem(XlspaceshipusergetAllOpponentUsersSpaceShips spaceShipsItem) {
    this.spaceShips.add(spaceShipsItem);
    return this;
  }

   /**
   * Get spaceShips
   * @return spaceShips
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<XlspaceshipusergetAllOpponentUsersSpaceShips> getSpaceShips() {
    return spaceShips;
  }

  public void setSpaceShips(List<XlspaceshipusergetAllOpponentUsersSpaceShips> spaceShips) {
    this.spaceShips = spaceShips;
  }

  public UserVo userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserVo userVo = (UserVo) o;
    return Objects.equals(this.fullName, userVo.fullName) &&
        Objects.equals(this.id, userVo.id) &&
        Objects.equals(this.password, userVo.password) &&
        Objects.equals(this.spaceShips, userVo.spaceShips) &&
        Objects.equals(this.userId, userVo.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullName, id, password, spaceShips, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserVo {\n");

    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    spaceShips: ").append(toIndentedString(spaceShips)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

