version: '2.1'
services:
 db:
    image: mysql:latest
    container_name: mysql-server
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
    - 3307:3306
    volumes:
    - ./db-sript.sql:/tmp/db-sript.sql
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d