/*
 * Spaceship API
 * Spaceship API help for commincate between spaceships
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.spaceship.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * InlineResponse2002
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-18T19:52:26.338Z")
public class InlineResponse2002 {
  @SerializedName("isAlive")
  private Boolean isAlive = null;

  @SerializedName("salvoShots")
  private List<InlineResponse2002SalvoShots> salvoShots = new ArrayList<InlineResponse2002SalvoShots>();

  public InlineResponse2002 isAlive(Boolean isAlive) {
    this.isAlive = isAlive;
    return this;
  }

   /**
   * Get isAlive
   * @return isAlive
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsAlive() {
    return isAlive;
  }

  public void setIsAlive(Boolean isAlive) {
    this.isAlive = isAlive;
  }

  public InlineResponse2002 salvoShots(List<InlineResponse2002SalvoShots> salvoShots) {
    this.salvoShots = salvoShots;
    return this;
  }

  public InlineResponse2002 addSalvoShotsItem(InlineResponse2002SalvoShots salvoShotsItem) {
    this.salvoShots.add(salvoShotsItem);
    return this;
  }

   /**
   * Get salvoShots
   * @return salvoShots
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<InlineResponse2002SalvoShots> getSalvoShots() {
    return salvoShots;
  }

  public void setSalvoShots(List<InlineResponse2002SalvoShots> salvoShots) {
    this.salvoShots = salvoShots;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.isAlive, inlineResponse2002.isAlive) &&
        Objects.equals(this.salvoShots, inlineResponse2002.salvoShots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isAlive, salvoShots);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");

    sb.append("    isAlive: ").append(toIndentedString(isAlive)).append("\n");
    sb.append("    salvoShots: ").append(toIndentedString(salvoShots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

