/*
 * Spaceship API
 * Spaceship API help for commincate between spaceships
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.spaceship.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * SpaceshipBoardResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-18T19:52:26.338Z")
public class SpaceshipBoardResponse {
    @SerializedName("board")
    private List<List<String>> board = new ArrayList<List<String>>();

  @SerializedName("boardLocked")
  private Boolean boardLocked = null;

    @SerializedName("spaceships")
    private List<String> spaceships = new ArrayList<String>();

    public SpaceshipBoardResponse board(List<List<String>> board) {
        this.board = board;
        return this;
    }

    public SpaceshipBoardResponse addBoardItem(List<String> boardItem) {
        this.board.add(boardItem);
        return this;
    }

    /**
     * Get board
     *
     * @return board
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<List<String>> getBoard() {
        return board;
    }

    public void setBoard(List<List<String>> board) {
        this.board = board;
    }

  public SpaceshipBoardResponse boardLocked(Boolean boardLocked) {
    this.boardLocked = boardLocked;
    return this;
  }

   /**
   * Get boardLocked
   * @return boardLocked
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getBoardLocked() {
    return boardLocked;
  }

  public void setBoardLocked(Boolean boardLocked) {
    this.boardLocked = boardLocked;
  }

  public SpaceshipBoardResponse spaceships(List<String> spaceships) {
    this.spaceships = spaceships;
    return this;
  }

  public SpaceshipBoardResponse addSpaceshipsItem(String spaceshipsItem) {
    this.spaceships.add(spaceshipsItem);
    return this;
  }

   /**
   * Get spaceships
   * @return spaceships
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getSpaceships() {
    return spaceships;
  }

  public void setSpaceships(List<String> spaceships) {
    this.spaceships = spaceships;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpaceshipBoardResponse spaceshipBoardResponse = (SpaceshipBoardResponse) o;
    return Objects.equals(this.board, spaceshipBoardResponse.board) &&
        Objects.equals(this.boardLocked, spaceshipBoardResponse.boardLocked) &&
        Objects.equals(this.spaceships, spaceshipBoardResponse.spaceships);
  }

  @Override
  public int hashCode() {
    return Objects.hash(board, boardLocked, spaceships);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpaceshipBoardResponse {\n");

    sb.append("    board: ").append(toIndentedString(board)).append("\n");
    sb.append("    boardLocked: ").append(toIndentedString(boardLocked)).append("\n");
    sb.append("    spaceships: ").append(toIndentedString(spaceships)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

