/*
 * Spaceship API
 * Spaceship API help for commincate between spaceships
 * OpenAPI spec version: 1.0
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.spaceship.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * SpaceshipRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-18T19:52:26.338Z")
public class SpaceshipRequest {
    @SerializedName("spaceShipName")
    private String spaceShipName = null;

    @SerializedName("xCoordinate")
    private Integer xCoordinate = null;

    @SerializedName("yCoordinate")
    private Integer yCoordinate = null;

    public SpaceshipRequest spaceShipName(String spaceShipName) {
        this.spaceShipName = spaceShipName;
        return this;
    }

    /**
     * Get spaceShipName
     *
     * @return spaceShipName
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getSpaceShipName() {
        return spaceShipName;
    }

    public void setSpaceShipName(String spaceShipName) {
        this.spaceShipName = spaceShipName;
    }

    public SpaceshipRequest xCoordinate(Integer xCoordinate) {
        this.xCoordinate = xCoordinate;
        return this;
    }

    /**
     * Get xCoordinate
     *
     * @return xCoordinate
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getXCoordinate() {
        return xCoordinate;
    }

    public void setXCoordinate(Integer xCoordinate) {
        this.xCoordinate = xCoordinate;
    }

    public SpaceshipRequest yCoordinate(Integer yCoordinate) {
        this.yCoordinate = yCoordinate;
        return this;
    }

    /**
     * Get yCoordinate
     *
     * @return yCoordinate
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getYCoordinate() {
        return yCoordinate;
    }

    public void setYCoordinate(Integer yCoordinate) {
        this.yCoordinate = yCoordinate;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SpaceshipRequest spaceshipRequest = (SpaceshipRequest) o;
        return Objects.equals(this.spaceShipName, spaceshipRequest.spaceShipName) && Objects.equals(this.xCoordinate, spaceshipRequest.xCoordinate)
                && Objects.equals(this.yCoordinate, spaceshipRequest.yCoordinate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(spaceShipName, xCoordinate, yCoordinate);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SpaceshipRequest {\n");

        sb.append("    spaceShipName: ").append(toIndentedString(spaceShipName)).append("\n");
        sb.append("    xCoordinate: ").append(toIndentedString(xCoordinate)).append("\n");
        sb.append("    yCoordinate: ").append(toIndentedString(yCoordinate)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
