/*
 * Spaceship API
 * Spaceship API help for commincate between spaceships
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.spaceship.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Spaceship
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-18T19:52:26.338Z")
public class Spaceship {
  @SerializedName("spaceshipAddress")
  private String spaceshipAddress = null;

  @SerializedName("spaceshipId")
  private Long spaceshipId = null;

  /**
   * Gets or Sets spaceshipStatus
   */
  public enum SpaceshipStatusEnum {
    @SerializedName("ACTIVE")
    ACTIVE("ACTIVE"),

    @SerializedName("INACTIVE")
    INACTIVE("INACTIVE");

    private String value;

    SpaceshipStatusEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("spaceshipStatus")
  private SpaceshipStatusEnum spaceshipStatus = null;

  @SerializedName("userId")
  private String userId = null;

  public Spaceship spaceshipAddress(String spaceshipAddress) {
    this.spaceshipAddress = spaceshipAddress;
    return this;
  }

   /**
   * Get spaceshipAddress
   * @return spaceshipAddress
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSpaceshipAddress() {
    return spaceshipAddress;
  }

  public void setSpaceshipAddress(String spaceshipAddress) {
    this.spaceshipAddress = spaceshipAddress;
  }

  public Spaceship spaceshipId(Long spaceshipId) {
    this.spaceshipId = spaceshipId;
    return this;
  }

   /**
   * Get spaceshipId
   * @return spaceshipId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSpaceshipId() {
    return spaceshipId;
  }

  public void setSpaceshipId(Long spaceshipId) {
    this.spaceshipId = spaceshipId;
  }

  public Spaceship spaceshipStatus(SpaceshipStatusEnum spaceshipStatus) {
    this.spaceshipStatus = spaceshipStatus;
    return this;
  }

   /**
   * Get spaceshipStatus
   * @return spaceshipStatus
  **/
  @ApiModelProperty(example = "null", value = "")
  public SpaceshipStatusEnum getSpaceshipStatus() {
    return spaceshipStatus;
  }

  public void setSpaceshipStatus(SpaceshipStatusEnum spaceshipStatus) {
    this.spaceshipStatus = spaceshipStatus;
  }

  public Spaceship userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Spaceship spaceship = (Spaceship) o;
    return Objects.equals(this.spaceshipAddress, spaceship.spaceshipAddress) &&
        Objects.equals(this.spaceshipId, spaceship.spaceshipId) &&
        Objects.equals(this.spaceshipStatus, spaceship.spaceshipStatus) &&
        Objects.equals(this.userId, spaceship.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(spaceshipAddress, spaceshipId, spaceshipStatus, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Spaceship {\n");

    sb.append("    spaceshipAddress: ").append(toIndentedString(spaceshipAddress)).append("\n");
    sb.append("    spaceshipId: ").append(toIndentedString(spaceshipId)).append("\n");
    sb.append("    spaceshipStatus: ").append(toIndentedString(spaceshipStatus)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

