/*
 * Spaceship API
 * Spaceship API help for commincate between spaceships
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.spaceship.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * XLSpaceshipRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-18T19:52:26.338Z")
public class XLSpaceshipRequest {
  @SerializedName("spaceShipId")
  private Long spaceShipId = null;

  @SerializedName("userId")
  private String userId = null;

  public XLSpaceshipRequest spaceShipId(Long spaceShipId) {
    this.spaceShipId = spaceShipId;
    return this;
  }

   /**
   * Get spaceShipId
   * @return spaceShipId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getSpaceShipId() {
    return spaceShipId;
  }

  public void setSpaceShipId(Long spaceShipId) {
    this.spaceShipId = spaceShipId;
  }

  public XLSpaceshipRequest userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XLSpaceshipRequest xLSpaceshipRequest = (XLSpaceshipRequest) o;
    return Objects.equals(this.spaceShipId, xLSpaceshipRequest.spaceShipId) &&
        Objects.equals(this.userId, xLSpaceshipRequest.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(spaceShipId, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XLSpaceshipRequest {\n");

    sb.append("    spaceShipId: ").append(toIndentedString(spaceShipId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

